const int t;

<<DFD>> R{"LegitPacketsLost"}max=? [ Fc time=maxTime ]

<<DFD>> R{"LegitPacketsLost"}min=? [ Fc time=maxTime ]

<<DFD>> R{"BogusPacketsLost"}max=? [ Fc time=maxTime ]

<<DFD>> R{"BogusPacketsLost"}min=? [ Fc time=maxTime ]

<<DFD>> R{"LegitPacketsProcessed"}max=? [ Fc time=maxTime ]

<<DFD>> R{"LegitPacketsProcessed"}min=? [ Fc time=maxTime ]

<<DFD>> R{"BogusPacketsProcessed"}max=? [ Fc time=maxTime ]

<<DFD>> R{"BogusPacketsProcessed"}min=? [ Fc time=maxTime ]

