/* PrismParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. PrismParserTokenManager.java */
package parser;
import java.io.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import jltl2ba.SimpleLTL;
import parser.BooleanUtils;
import parser.ast.*;
import parser.type.*;
import prism.ModelInfo;
import parser.visitor.*;
import prism.ModelType;
import prism.PrismLangException;

/** Token Manager. */
@SuppressWarnings ("unused")
public class PrismParserTokenManager implements PrismParserConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x7f01001170004408L) != 0L || (active1 & 0x607f80L) != 0L)
            return 31;
         if ((active1 & 0x40000000000000L) != 0L)
            return 1;
         if ((active0 & 0x80feffee8fffbbf0L) != 0L || (active1 & 0x9f807fL) != 0L)
         {
            jjmatchedKind = 126;
            return 31;
         }
         if ((active1 & 0x400000000L) != 0L)
            return 32;
         return -1;
      case 1:
         if ((active0 & 0x260000000L) != 0L)
            return 31;
         if ((active0 & 0xbffeffec8fffbbf0L) != 0L || (active1 & 0x9f9fffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 126;
               jjmatchedPos = 1;
            }
            return 31;
         }
         return -1;
      case 2:
         if ((active0 & 0x7f4000000080L) != 0L || (active1 & 0x820010L) != 0L)
            return 31;
         if ((active0 & 0xbffe80ac8fffbb70L) != 0L || (active1 & 0x1d9fefL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 126;
               jjmatchedPos = 2;
            }
            return 31;
         }
         return -1;
      case 3:
         if ((active0 & 0x3f00000408002910L) != 0L || (active1 & 0x191facL) != 0L)
            return 31;
         if ((active0 & 0x80feb3a887ff9260L) != 0L || (active1 & 0x48043L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 126;
               jjmatchedPos = 3;
            }
            return 31;
         }
         return -1;
      case 4:
         if ((active0 & 0x8001000260L) != 0L || (active1 & 0x3L) != 0L)
            return 31;
         if ((active0 & 0x9bfeb32886ff9000L) != 0L || (active1 & 0x48dc4L) != 0L)
         {
            jjmatchedKind = 126;
            jjmatchedPos = 4;
            return 31;
         }
         return -1;
      case 5:
         if ((active0 & 0x8000b30084001000L) != 0L || (active1 & 0x40000L) != 0L)
            return 31;
         if ((active0 & 0x1bfe002802ff8000L) != 0L || (active1 & 0x8dc4L) != 0L)
         {
            jjmatchedKind = 126;
            jjmatchedPos = 5;
            return 31;
         }
         return -1;
      case 6:
         if ((active0 & 0x1b00000002010000L) != 0L || (active1 & 0xdc0L) != 0L)
            return 31;
         if ((active0 & 0xfe002800fe8000L) != 0L || (active1 & 0x8004L) != 0L)
         {
            jjmatchedKind = 126;
            jjmatchedPos = 6;
            return 31;
         }
         return -1;
      case 7:
         if ((active0 & 0x2000800000L) != 0L)
            return 31;
         if ((active0 & 0xfe0008007e8000L) != 0L || (active1 & 0x8004L) != 0L)
         {
            jjmatchedKind = 126;
            jjmatchedPos = 7;
            return 31;
         }
         return -1;
      case 8:
         if ((active0 & 0x70000800540000L) != 0L)
            return 31;
         if ((active0 & 0x8e0000002a8000L) != 0L || (active1 & 0x8004L) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 126;
               jjmatchedPos = 8;
            }
            return 31;
         }
         return -1;
      case 9:
         if ((active0 & 0xcc000000200000L) != 0L || (active1 & 0x8000L) != 0L)
            return 31;
         if ((active0 & 0x20000000a8000L) != 0L || (active1 & 0x4L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 126;
               jjmatchedPos = 9;
            }
            return 31;
         }
         return -1;
      case 10:
         if ((active0 & 0x8000000008000L) != 0L)
            return 31;
         if ((active0 & 0x20000000a0000L) != 0L || (active1 & 0x4L) != 0L)
         {
            jjmatchedKind = 126;
            jjmatchedPos = 10;
            return 31;
         }
         return -1;
      case 11:
         if ((active0 & 0x20000L) != 0L)
            return 31;
         if ((active0 & 0x2000000080000L) != 0L || (active1 & 0x4L) != 0L)
         {
            jjmatchedKind = 126;
            jjmatchedPos = 11;
            return 31;
         }
         return -1;
      case 12:
         if ((active1 & 0x4L) != 0L)
            return 31;
         if ((active0 & 0x2000000080000L) != 0L)
         {
            jjmatchedKind = 126;
            jjmatchedPos = 12;
            return 31;
         }
         return -1;
      case 13:
         if ((active0 & 0x80000L) != 0L)
            return 31;
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 126;
            jjmatchedPos = 13;
            return 31;
         }
         return -1;
      case 14:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 126;
            jjmatchedPos = 14;
            return 31;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 88;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000000L);
      case 34:
         return jjStopAtPos(0, 122);
      case 38:
         return jjStopAtPos(0, 89);
      case 39:
         return jjStopAtPos(0, 119);
      case 40:
         return jjStopAtPos(0, 99);
      case 41:
         return jjStopAtPos(0, 100);
      case 42:
         return jjStopAtPos(0, 117);
      case 43:
         return jjStopAtPos(0, 115);
      case 44:
         return jjStopAtPos(0, 97);
      case 45:
         jjmatchedKind = 116;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x60000000L);
      case 46:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400000000L);
      case 47:
         return jjStartNfaWithStates_0(0, 118, 1);
      case 58:
         return jjStopAtPos(0, 95);
      case 59:
         return jjStopAtPos(0, 96);
      case 60:
         jjmatchedKind = 109;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x102800010000000L);
      case 61:
         jjmatchedKind = 107;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000L);
      case 62:
         jjmatchedKind = 110;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x5000000000000L);
      case 63:
         return jjStopAtPos(0, 121);
      case 65:
         return jjStartNfaWithStates_0(0, 3, 31);
      case 67:
         return jjStartNfaWithStates_0(0, 10, 31);
      case 69:
         return jjStartNfaWithStates_0(0, 14, 31);
      case 70:
         jjmatchedKind = 28;
         return jjMoveStringLiteralDfa1_0(0x60000000L, 0x0L);
      case 71:
         return jjStartNfaWithStates_0(0, 32, 31);
      case 73:
         return jjStartNfaWithStates_0(0, 36, 31);
      case 80:
         jjmatchedKind = 62;
         return jjMoveStringLiteralDfa1_0(0x3f00000000000000L, 0x0L);
      case 82:
         jjmatchedKind = 77;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1f80L);
      case 83:
         return jjStartNfaWithStates_0(0, 78, 31);
      case 85:
         return jjStartNfaWithStates_0(0, 85, 31);
      case 87:
         return jjStartNfaWithStates_0(0, 86, 31);
      case 88:
         return jjStartNfaWithStates_0(0, 48, 31);
      case 91:
         jjmatchedKind = 101;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000000L);
      case 93:
         jjmatchedKind = 102;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000000000L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x10L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x3e0L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x3800L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0xff8000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0xf000000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x6e00000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x8000000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0xff0000000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x1c000000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x8080000000000000L, 0x1fL);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x60L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x78000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x180000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x60000000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 105);
      case 124:
         return jjStopAtPos(0, 90);
      case 125:
         return jjStopAtPos(0, 106);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 45:
         if ((active1 & 0x100000000000000L) != 0L)
            return jjStopAtPos(1, 120);
         break;
      case 46:
         if ((active1 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 98);
         break;
      case 48:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(1, 30, 31);
         break;
      case 60:
         if ((active1 & 0x800000000000L) != 0L)
            return jjStopAtPos(1, 111);
         break;
      case 61:
         if ((active1 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 108);
         else if ((active1 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 113;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 114);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10000000L);
      case 62:
         if ((active1 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 91);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 93);
         else if ((active1 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 112);
         break;
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000000L);
      case 91:
         if ((active1 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 103);
         break;
      case 93:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 104);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x80078001000000L, active1, 0x20L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0xc000000000000L, active1, 0x800000L);
      case 99:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(1, 29, 31);
         break;
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40L);
      case 102:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(1, 33, 31);
         break;
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x700004000800L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000080000020L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x3f00000000000000L, active1, 0x21f80L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x60006c007f8000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x2800002001050L, active1, 0x3L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80000L);
      case 113:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10000cL);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000002300L, active1, 0x18010L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x40000000L);
      case 62:
         if ((active1 & 0x10000000L) != 0L)
            return jjStopAtPos(2, 92);
         break;
      case 97:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(2, 68, 31);
         return jjMoveStringLiteralDfa3_0(active0, 0x8700000000000000L, active1, 0x380L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x60000000000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000007f8000L, active1, 0L);
      case 103:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 31);
         else if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(2, 81, 31);
         break;
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x3800000400000000L, active1, 0x1c00L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x2300L, active1, 0x1L);
      case 110:
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x2300008000040L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000030L, active1, 0x800cL);
      case 112:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 43, 31);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x10002L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000002000000L, active1, 0L);
      case 115:
         if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 87, 31);
         return jjMoveStringLiteralDfa3_0(active0, 0xc002000000800L, active1, 0x40000L);
      case 116:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 38, 31);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x80020L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x801000L, active1, 0x100000L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x40L);
      case 120:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x30000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 62:
         if ((active1 & 0x40000000L) != 0L)
            return jjStopAtPos(3, 94);
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000800800000L, active1, 0x40L);
      case 98:
         if ((active1 & 0x8L) != 0L)
         {
            jjmatchedKind = 67;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x80001000L, active1, 0x4L);
      case 99:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 31);
         else if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 31);
         else if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 13, 31);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(3, 27, 31);
         return jjMoveStringLiteralDfa4_0(active0, 0x20L, active1, 0x8000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000200L, active1, 0x1L);
      case 101:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 69, 31);
         else if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 84, 31);
         return jjMoveStringLiteralDfa4_0(active0, 0x7c008000008000L, active1, 0L);
      case 103:
         if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 80, 31);
         else if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 83, 31);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x30000L, active1, 0L);
      case 108:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 31);
         break;
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x330002040000L, active1, 0L);
      case 110:
         if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 61;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x1000L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1800000000000000L, active1, 0xc00L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x1400040L, active1, 0L);
      case 116:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 31);
         return jjMoveStringLiteralDfa4_0(active0, 0x2004000000L, active1, 0x40002L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L, active1, 0L);
      case 120:
         if ((active0 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x300000000000000L, active1, 0x180L);
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(4, 65, 31);
         return jjMoveStringLiteralDfa5_0(active0, 0x112080000000L, active1, 0x4L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000L, active1, 0L);
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(4, 24, 31);
         return jjMoveStringLiteralDfa5_0(active0, 0x8002000004200000L, active1, 0x40000L);
      case 104:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x220000000000L, active1, 0L);
      case 107:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 5, 31);
         break;
      case 108:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 39, 31);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000101000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x1b80000000000000L, active1, 0xd80L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x30000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L, active1, 0L);
      case 112:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 31);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(4, 64, 31);
         break;
      case 113:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x7c000800000000L, active1, 0x40L);
      case 116:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 31);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x900000000100000L, active1, 0x8480L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x4L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000L, active1, 0x40L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 12, 31);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 47, 31);
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x1200000800810000L, active1, 0x900L);
      case 108:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 31);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L, active1, 0L);
      case 109:
         if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 82, 31);
         break;
      case 110:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 41, 31);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 31);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L, active1, 0L);
      case 114:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 31);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 63, 31);
         break;
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x480000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x62000000000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0xc000000020000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000200000L, active1, 0L);
      case 120:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 40, 31);
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 44, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(6, 25, 31);
         return jjMoveStringLiteralDfa7_0(active0, 0x6c000800228000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000080000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000000L, active1, 0x4L);
      case 110:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 57, 31);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 60, 31);
         else if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(6, 72, 31);
         else if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(6, 75, 31);
         break;
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L, active1, 0L);
      case 115:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(6, 70, 31);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x8000L);
      case 116:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(6, 16, 31);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000400000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000L, active1, 0L);
      case 120:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 56, 31);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 59, 31);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(6, 71, 31);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(6, 74, 31);
         break;
      case 121:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa8_0(active0, 0xc000000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 37, 31);
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000500000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x60000000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000L, active1, 0x4L);
      case 110:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(7, 23, 31);
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000002a0000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L, active1, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000L, active1, 0L);
      case 101:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(8, 18, 31);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 52, 31);
         break;
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x28000L, active1, 0x8004L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0xc000000000000L, active1, 0L);
      case 109:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(8, 22, 31);
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000000L, active1, 0L);
      case 114:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(8, 20, 31);
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(8, 35, 31);
         break;
      case 118:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0xa0000L, active1, 0L);
      case 99:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(9, 79, 31);
         break;
      case 101:
         if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000L, active1, 0L);
      case 115:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(9, 21, 31);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 54, 31);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 55, 31);
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa11_0(active0, 0x80000L, active1, 0L);
      case 110:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(10, 15, 31);
         return jjMoveStringLiteralDfa11_0(active0, 0x2000000020000L, active1, 0L);
      case 115:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 51, 31);
         break;
      case 116:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1);
      return 11;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000000000000L, active1, 0x4L);
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0x80000L, active1, 0L);
      case 116:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(11, 17, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, active1);
      return 12;
   }
   switch(curChar)
   {
      case 99:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(12, 66, 31);
         break;
      case 101:
         return jjMoveStringLiteralDfa13_0(active0, 0x80000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, active1);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(11, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 115:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(13, 19, 31);
         break;
      case 116:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa15_0(active0, 0x2000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(15, 49, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(14, active0, 0L);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 31;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 126)
                        kind = 126;
                     { jjCheckNAdd(25); }
                  }
                  else if (curChar == 39)
                  {
                     if (kind > 125)
                        kind = 125;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 128)
                        kind = 128;
                     { jjCheckNAddTwoStates(18, 19); }
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAddTwoStates(14, 15); }
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAddStates(0, 7); }
                  }
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if (curChar == 46)
                     { jjCheckNAddTwoStates(14, 18); }
                  else if (curChar == 35)
                     { jjCheckNAddTwoStates(11, 12); }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 1;
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     { jjCheckNAdd(8); }
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 123)
                        kind = 123;
                  }
                  break;
               case 1:
                  if (curChar != 47)
                     break;
                  if (kind > 2)
                     kind = 2;
                  { jjCheckNAddStates(8, 10); }
                  break;
               case 2:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  { jjCheckNAddStates(8, 10); }
                  break;
               case 3:
                  if ((0x2400L & l) != 0L && kind > 2)
                     kind = 2;
                  break;
               case 4:
                  if (curChar == 10 && kind > 2)
                     kind = 2;
                  break;
               case 5:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 7:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  { jjCheckNAdd(8); }
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  { jjCheckNAdd(8); }
                  break;
               case 9:
                  if (curChar == 48 && kind > 123)
                     kind = 123;
                  break;
               case 10:
                  if (curChar == 35)
                     { jjCheckNAddTwoStates(11, 12); }
                  break;
               case 11:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(11, 12); }
                  break;
               case 12:
                  if (curChar == 35 && kind > 127)
                     kind = 127;
                  break;
               case 13:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(14, 18); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 124)
                     kind = 124;
                  { jjCheckNAddTwoStates(14, 15); }
                  break;
               case 16:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(17); }
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 124)
                     kind = 124;
                  { jjCheckNAdd(17); }
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 128)
                     kind = 128;
                  { jjCheckNAddTwoStates(18, 19); }
                  break;
               case 20:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(21); }
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 128)
                     kind = 128;
                  { jjCheckNAdd(21); }
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 24:
                  if (curChar == 39 && kind > 125)
                     kind = 125;
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 126)
                     kind = 126;
                  { jjCheckNAdd(25); }
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 124)
                     kind = 124;
                  { jjCheckNAddStates(0, 7); }
                  break;
               case 27:
                  if (curChar == 46)
                     { jjCheckNAdd(14); }
                  break;
               case 28:
                  if (curChar == 46)
                     { jjCheckNAdd(18); }
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 128)
                     kind = 128;
                  { jjCheckNAddStates(11, 14); }
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 124)
                     kind = 124;
                  { jjCheckNAddStates(15, 18); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 31:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 126)
                        kind = 126;
                     { jjCheckNAdd(25); }
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 126)
                     kind = 126;
                  { jjCheckNAddStates(19, 21); }
                  break;
               case 2:
                  if (kind > 2)
                     kind = 2;
                  { jjAddStates(8, 10); }
                  break;
               case 11:
                  { jjAddStates(22, 23); }
                  break;
               case 15:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(24, 25); }
                  break;
               case 19:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(26, 27); }
                  break;
               case 23:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 25:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 126)
                     kind = 126;
                  { jjCheckNAdd(25); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 2)
                     kind = 2;
                  { jjAddStates(8, 10); }
                  break;
               case 11:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(22, 23); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 31 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, "\101", "\142\157\157\154", "\143\154\157\143\153", 
"\143\157\156\163\164", "\143\163\147", "\143\164\155\143", "\143\164\155\144\160", "\103", 
"\144\151\163\143", "\144\157\165\142\154\145", "\144\164\155\143", "\105", 
"\145\156\144\145\161\165\141\164\151\157\156", "\145\156\144\151\156\151\164", 
"\145\156\144\151\156\166\141\162\151\141\156\164", "\145\156\144\155\157\144\165\154\145", 
"\145\156\144\157\142\163\145\162\166\141\142\154\145\163", "\145\156\144\160\154\141\171\145\162", 
"\145\156\144\162\145\167\141\162\144\163", "\145\156\144\163\171\163\164\145\155", "\145\161\165\141\164\151\157\156", 
"\146\141\154\163\145", "\146\157\162\155\165\154\141", "\146\151\154\164\145\162", 
"\146\165\156\143", "\106", "\106\143", "\106\60", "\147\154\157\142\141\154", "\107", "\151\146", 
"\151\156\151\164", "\151\156\166\141\162\151\141\156\164", "\111", 
"\151\156\163\164\141\156\143\145", "\151\156\164", "\154\141\142\145\154", "\155\141\170\155\141\170", 
"\155\141\170\155\151\156", "\155\141\170", "\155\144\160", "\155\151\156\155\141\170", 
"\155\151\156\155\151\156", "\155\151\156", "\155\157\144\165\154\145", "\130", 
"\156\157\156\144\145\164\145\162\155\151\156\151\163\164\151\143", "\157\142\163\145\162\166\141\142\154\145", 
"\157\142\163\145\162\166\141\142\154\145\163", "\157\164\150\145\162\167\151\163\145", 
"\165\156\143\145\162\164\141\151\156", "\165\156\143\145\162\164\141\151\156\163", 
"\160\141\162\141\155\145\164\145\162\163", "\120\155\141\170\155\141\170", "\120\155\141\170\155\151\156", 
"\120\155\141\170", "\120\155\151\156\155\141\170", "\120\155\151\156\155\151\156", 
"\120\155\151\156", "\120", "\160\154\141\171\145\162", "\160\157\155\144\160", 
"\160\157\160\164\141", "\160\162\157\142\141\142\151\154\151\163\164\151\143", "\160\162\157\142", 
"\160\164\141", "\162\141\164\145", "\162\145\167\141\162\144\163", 
"\122\155\141\170\155\141\170", "\122\155\141\170\155\151\156", "\122\155\141\170", 
"\122\155\151\156\155\141\170", "\122\155\151\156\155\151\156", "\122\155\151\156", "\122", "\123", 
"\163\164\157\143\150\141\163\164\151\143", "\163\164\160\147", "\163\155\147", "\163\171\163\164\145\155", 
"\164\160\164\147", "\164\162\165\145", "\125", "\127", "\141\142\163", "\41", "\46", "\174", 
"\75\76", "\74\75\76", "\55\76", "\55\125\55\76", "\72", "\73", "\54", "\56\56", "\50", 
"\51", "\133", "\135", "\133\133", "\135\135", "\173", "\175", "\75", "\41\75", 
"\74", "\76", "\74\74", "\76\76", "\74\75", "\76\75", "\53", "\55", "\52", "\57", 
"\47", "\74\55", "\77", "\42", null, null, null, null, null, null, null, };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   27, 14, 15, 28, 18, 19, 29, 30, 2, 3, 5, 28, 18, 19, 29, 27, 
   14, 15, 30, 23, 24, 25, 11, 12, 16, 17, 20, 21, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 129)
   {
      jjmatchedKind = 129;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public PrismParserTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public PrismParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 31; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffffffff9L, 0xffffffffffffffffL, 0x3L, 
};
static final long[] jjtoSkip = {
   0x6L, 0x0L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x6L, 0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 0x0L, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[31];
    static private final int[] jjstateSet = new int[2 * 31];
    private static final StringBuilder jjimage = new StringBuilder();
    private static StringBuilder image = jjimage;
    private static int jjimageLen;
    private static int lengthOfMatch;
    static protected int curChar;
}
