/* Generated By:JavaCC: Do not edit this line. PrismParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PrismParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int COMMENT = 2;
  /** RegularExpression Id. */
  int A = 3;
  /** RegularExpression Id. */
  int BOOL = 4;
  /** RegularExpression Id. */
  int CLOCK = 5;
  /** RegularExpression Id. */
  int CONST = 6;
  /** RegularExpression Id. */
  int CSG = 7;
  /** RegularExpression Id. */
  int CTMC = 8;
  /** RegularExpression Id. */
  int CTMDP = 9;
  /** RegularExpression Id. */
  int C = 10;
  /** RegularExpression Id. */
  int DISCOUNT = 11;
  /** RegularExpression Id. */
  int DOUBLE = 12;
  /** RegularExpression Id. */
  int DTMC = 13;
  /** RegularExpression Id. */
  int E = 14;
  /** RegularExpression Id. */
  int ENDEQUATION = 15;
  /** RegularExpression Id. */
  int ENDINIT = 16;
  /** RegularExpression Id. */
  int ENDINVARIANT = 17;
  /** RegularExpression Id. */
  int ENDMODULE = 18;
  /** RegularExpression Id. */
  int ENDOBSERVABLES = 19;
  /** RegularExpression Id. */
  int ENDPLAYER = 20;
  /** RegularExpression Id. */
  int ENDREWARDS = 21;
  /** RegularExpression Id. */
  int ENDSYSTEM = 22;
  /** RegularExpression Id. */
  int EQUATION = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int FORMULA = 25;
  /** RegularExpression Id. */
  int FILTER = 26;
  /** RegularExpression Id. */
  int FUNC = 27;
  /** RegularExpression Id. */
  int F = 28;
  /** RegularExpression Id. */
  int Fc = 29;
  /** RegularExpression Id. */
  int F0 = 30;
  /** RegularExpression Id. */
  int GLOBAL = 31;
  /** RegularExpression Id. */
  int G = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int INIT = 34;
  /** RegularExpression Id. */
  int INVARIANT = 35;
  /** RegularExpression Id. */
  int I = 36;
  /** RegularExpression Id. */
  int INSTANCE = 37;
  /** RegularExpression Id. */
  int INT = 38;
  /** RegularExpression Id. */
  int LABEL = 39;
  /** RegularExpression Id. */
  int MAXMAX = 40;
  /** RegularExpression Id. */
  int MAXMIN = 41;
  /** RegularExpression Id. */
  int MAX = 42;
  /** RegularExpression Id. */
  int MDP = 43;
  /** RegularExpression Id. */
  int MINMAX = 44;
  /** RegularExpression Id. */
  int MINMIN = 45;
  /** RegularExpression Id. */
  int MIN = 46;
  /** RegularExpression Id. */
  int MODULE = 47;
  /** RegularExpression Id. */
  int X = 48;
  /** RegularExpression Id. */
  int NONDETERMINISTIC = 49;
  /** RegularExpression Id. */
  int OBSERVABLE = 50;
  /** RegularExpression Id. */
  int OBSERVABLES = 51;
  /** RegularExpression Id. */
  int OTHERWISE = 52;
  /** RegularExpression Id. */
  int UNCERTAIN = 53;
  /** RegularExpression Id. */
  int UNCERTAINS = 54;
  /** RegularExpression Id. */
  int PARAMETERS = 55;
  /** RegularExpression Id. */
  int PMAXMAX = 56;
  /** RegularExpression Id. */
  int PMAXMIN = 57;
  /** RegularExpression Id. */
  int PMAX = 58;
  /** RegularExpression Id. */
  int PMINMAX = 59;
  /** RegularExpression Id. */
  int PMINMIN = 60;
  /** RegularExpression Id. */
  int PMIN = 61;
  /** RegularExpression Id. */
  int P = 62;
  /** RegularExpression Id. */
  int PLAYER = 63;
  /** RegularExpression Id. */
  int POMDP = 64;
  /** RegularExpression Id. */
  int POPTA = 65;
  /** RegularExpression Id. */
  int PROBABILISTIC = 66;
  /** RegularExpression Id. */
  int PROB = 67;
  /** RegularExpression Id. */
  int PTA = 68;
  /** RegularExpression Id. */
  int RATE = 69;
  /** RegularExpression Id. */
  int REWARDS = 70;
  /** RegularExpression Id. */
  int RMAXMAX = 71;
  /** RegularExpression Id. */
  int RMAXMIN = 72;
  /** RegularExpression Id. */
  int RMAX = 73;
  /** RegularExpression Id. */
  int RMINMAX = 74;
  /** RegularExpression Id. */
  int RMINMIN = 75;
  /** RegularExpression Id. */
  int RMIN = 76;
  /** RegularExpression Id. */
  int R = 77;
  /** RegularExpression Id. */
  int S = 78;
  /** RegularExpression Id. */
  int STOCHASTIC = 79;
  /** RegularExpression Id. */
  int STPG = 80;
  /** RegularExpression Id. */
  int SMG = 81;
  /** RegularExpression Id. */
  int SYSTEM = 82;
  /** RegularExpression Id. */
  int TPTG = 83;
  /** RegularExpression Id. */
  int TRUE = 84;
  /** RegularExpression Id. */
  int U = 85;
  /** RegularExpression Id. */
  int W = 86;
  /** RegularExpression Id. */
  int ABS = 87;
  /** RegularExpression Id. */
  int NOT = 88;
  /** RegularExpression Id. */
  int AND = 89;
  /** RegularExpression Id. */
  int OR = 90;
  /** RegularExpression Id. */
  int IMPLIES = 91;
  /** RegularExpression Id. */
  int IFF = 92;
  /** RegularExpression Id. */
  int RARROW = 93;
  /** RegularExpression Id. */
  int URARROW = 94;
  /** RegularExpression Id. */
  int COLON = 95;
  /** RegularExpression Id. */
  int SEMICOLON = 96;
  /** RegularExpression Id. */
  int COMMA = 97;
  /** RegularExpression Id. */
  int DOTS = 98;
  /** RegularExpression Id. */
  int LPARENTH = 99;
  /** RegularExpression Id. */
  int RPARENTH = 100;
  /** RegularExpression Id. */
  int LBRACKET = 101;
  /** RegularExpression Id. */
  int RBRACKET = 102;
  /** RegularExpression Id. */
  int DLBRACKET = 103;
  /** RegularExpression Id. */
  int DRBRACKET = 104;
  /** RegularExpression Id. */
  int LBRACE = 105;
  /** RegularExpression Id. */
  int RBRACE = 106;
  /** RegularExpression Id. */
  int EQ = 107;
  /** RegularExpression Id. */
  int NE = 108;
  /** RegularExpression Id. */
  int LT = 109;
  /** RegularExpression Id. */
  int GT = 110;
  /** RegularExpression Id. */
  int DLT = 111;
  /** RegularExpression Id. */
  int DGT = 112;
  /** RegularExpression Id. */
  int LE = 113;
  /** RegularExpression Id. */
  int GE = 114;
  /** RegularExpression Id. */
  int PLUS = 115;
  /** RegularExpression Id. */
  int MINUS = 116;
  /** RegularExpression Id. */
  int TIMES = 117;
  /** RegularExpression Id. */
  int DIVIDE = 118;
  /** RegularExpression Id. */
  int PRIME = 119;
  /** RegularExpression Id. */
  int RENAME = 120;
  /** RegularExpression Id. */
  int QMARK = 121;
  /** RegularExpression Id. */
  int DQUOTE = 122;
  /** RegularExpression Id. */
  int REG_INT = 123;
  /** RegularExpression Id. */
  int REG_DOUBLE = 124;
  /** RegularExpression Id. */
  int REG_IDENTPRIME = 125;
  /** RegularExpression Id. */
  int REG_IDENT = 126;
  /** RegularExpression Id. */
  int PREPROC = 127;
  /** RegularExpression Id. */
  int COEFF = 128;
  /** RegularExpression Id. */
  int LEXICAL_ERROR = 129;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<COMMENT>",
    "\"A\"",
    "\"bool\"",
    "\"clock\"",
    "\"const\"",
    "\"csg\"",
    "\"ctmc\"",
    "\"ctmdp\"",
    "\"C\"",
    "\"disc\"",
    "\"double\"",
    "\"dtmc\"",
    "\"E\"",
    "\"endequation\"",
    "\"endinit\"",
    "\"endinvariant\"",
    "\"endmodule\"",
    "\"endobservables\"",
    "\"endplayer\"",
    "\"endrewards\"",
    "\"endsystem\"",
    "\"equation\"",
    "\"false\"",
    "\"formula\"",
    "\"filter\"",
    "\"func\"",
    "\"F\"",
    "\"Fc\"",
    "\"F0\"",
    "\"global\"",
    "\"G\"",
    "\"if\"",
    "\"init\"",
    "\"invariant\"",
    "\"I\"",
    "\"instance\"",
    "\"int\"",
    "\"label\"",
    "\"maxmax\"",
    "\"maxmin\"",
    "\"max\"",
    "\"mdp\"",
    "\"minmax\"",
    "\"minmin\"",
    "\"min\"",
    "\"module\"",
    "\"X\"",
    "\"nondeterministic\"",
    "\"observable\"",
    "\"observables\"",
    "\"otherwise\"",
    "\"uncertain\"",
    "\"uncertains\"",
    "\"parameters\"",
    "\"Pmaxmax\"",
    "\"Pmaxmin\"",
    "\"Pmax\"",
    "\"Pminmax\"",
    "\"Pminmin\"",
    "\"Pmin\"",
    "\"P\"",
    "\"player\"",
    "\"pomdp\"",
    "\"popta\"",
    "\"probabilistic\"",
    "\"prob\"",
    "\"pta\"",
    "\"rate\"",
    "\"rewards\"",
    "\"Rmaxmax\"",
    "\"Rmaxmin\"",
    "\"Rmax\"",
    "\"Rminmax\"",
    "\"Rminmin\"",
    "\"Rmin\"",
    "\"R\"",
    "\"S\"",
    "\"stochastic\"",
    "\"stpg\"",
    "\"smg\"",
    "\"system\"",
    "\"tptg\"",
    "\"true\"",
    "\"U\"",
    "\"W\"",
    "\"abs\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"<=>\"",
    "\"->\"",
    "\"-U->\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"[[\"",
    "\"]]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<<\"",
    "\">>\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"<-\"",
    "\"?\"",
    "\"\\\"\"",
    "<REG_INT>",
    "<REG_DOUBLE>",
    "<REG_IDENTPRIME>",
    "<REG_IDENT>",
    "<PREPROC>",
    "<COEFF>",
    "<LEXICAL_ERROR>",
  };

}
